version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: user-manager-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysuperdifficultpassword
      - MYSQL_DATABASE=user_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=mydifficultpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 